site_name: siria的非技术写作
site_author: leo
site_url: https://leosirius.github.io/non_tech_writing/
docs_dir: ./docs

repo_name: tech_writing
repo_url: https://github.com/LeoSirius/non_tech_writing/

theme:
  name: material
  favicon: logo.png
  logo: logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky

